import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import DarkVeil from "@/components/DarkVeil";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased text-[#ededed]`}
      >
        {/* 전역 배경 DarkVeil */}
        <div 
          style={{ 
            position: 'fixed', 
            top: 0, 
            left: 0, 
            width: '100%', 
            height: '100%', 
            zIndex: -1,
            pointerEvents: 'none'
          }}
        >
          <DarkVeil
            hueShift={217}
            noiseIntensity={0}
            scanlineIntensity={0}
            speed={2.1}
            scanlineFrequency={0.5}
            warpAmount={2.9}
          />
        </div>
        <div className="max-w-[1440px] mx-auto px-8">
          <Header />
          <main className="relative">{children}</main>
        </div>
      </body>
    </html>
  );
}
